apiVersion: skaffold/v2alpha3
kind: Config
# 쿠버네티스 배포 설정
deploy:
  kubectl:
    manifests:
      - ./xinfra/kubernetes/*
# 도커 이미지 빌드 관련 설정
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: molten-turbine-319402
  artifacts:
    - image: meliushp/getmem
      context: getmem
      docker:
        dockerfile: Dockerfile
    - image: meliushp/nodecheck
      context: nodecheck
      docker:
        dockerfile: Dockerfile
    - image: meliushp/sayservice
      context: sayservice
      docker:
        dockerfile: Dockerfile
    - image: meliushp/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      # 소스 싱크 관련 설정
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .